(enhancement) bump styling to carbon 11 for form-entry engine
openmrs/openmrs-ngx-formentry pull request #1
Opened 2022-08-29 11:43 UTC by donaldkibet

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

## Summary

- Update the styling of form-entry to Carbon 11

## Screenshots

*None.*

## Issue

*None.*

## Other

*None.*

2022-08-29 14:31 UTC, makombe approved these changes
LGTM

2022-08-29 14:32 UTC, makombe approved these changes

2022-08-29 16:57 UTC, ibacher requested changes
@donaldkibet Thanks for this! Some nit-picky changes are necessary, but broadly this looks good.

2022-08-29 16:57 UTC, ibacher commented on .github/workflows/main.yml
> +      - run: yarn install
```suggestion
      - run: yarn install --frozen-lockfile
```

2022-08-29 16:57 UTC, ibacher commented on .gitignore
> +.yarn
```suggestion
```

2022-08-29 16:57 UTC, ibacher commented on package.json
> +    "@carbon/styles": "1.x"
This should be a dependency, not a peer dependency (it isn't provided at runtime).

2022-08-29 16:57 UTC, ibacher commented on .gitignore
> +.yarn
If you're moving this repo over to Yarn 3, please see the Yarn docs for what needs to be in the .gitignore.

2022-08-29 16:57 UTC, ibacher commented on src/styles.scss
> +@import '~@carbon/styles/css/styles.min.css';
```suggestion
@import '~@carbon/styles';
```

2022-08-29 16:57 UTC, ibacher commented on .github/workflows/main.yml
> +      - run: yarn install
```suggestion
      - run: yarn install --frozen-lockfile
```

Or for Yarn v3:

```suggestion
      - run: yarn install --immutable
```

2022-08-30 12:04 UTC, ibacher commented on .github/workflows/main.yml
> +      - run: yarn install
The yarn lock files need to be updated, but that should be part of your commit. By the time CI is running, the yarn lock file shouldn't need to be updated (this is basically the use-case for this flag).

2022-08-31 09:15 UTC, denniskigen approved these changes

2022-08-31 15:06 UTC, ibacher approved these changes

2022-08-31 15:07 UTC, ibacher commented
Thanks @donaldkibet!

2022-08-31 15:07 UTC, merged